# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-c92fe1a4-6170-496c-a5bf-7c0de475861f";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-c92fe1a4-6170-496c-a5bf-7c0de475861f".device =
    "/dev/disk/by-uuid/c92fe1a4-6170-496c-a5bf-7c0de475861f";
  boot.initrd.luks.devices."luks-ca9b15a5-7f0e-431f-a8e4-68980f4ccf6d".device =
    "/dev/disk/by-uuid/ca9b15a5-7f0e-431f-a8e4-68980f4ccf6d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2F72-1BDB";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-ca9b15a5-7f0e-431f-a8e4-68980f4ccf6d"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
