# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.fwupd = {
    enable = true;
  };

  powerManagement = {
    enable = true;
    powertop.enable = false;
    cpuFreqGovernor = lib.mkForce "performance";
  };

  systemd.services.platform-profile-performance = {
    description = "Set ACPI platform profile to performance";
    wantedBy = [ "multi-user.target" ];
    serviceConfig.Type = "oneshot";

    script = ''
      if [ -w /sys/firmware/acpi/platform_profile ]; then
        choices="$(cat /sys/firmware/acpi/platform_profile_choices 2>/dev/null || true)"
        if echo "$choices" | grep -qw performance; then
          echo performance > /sys/firmware/acpi/platform_profile
        fi
      fi
    '';
  };

  systemd.services.rocm-high-performance = {
    description = "Set AMD GPU ROCm performance level to high";
    wantedBy = [ "multi-user.target" ];
    after = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      ${pkgs.rocmPackages.rocm-smi}/bin/rocm-smi --setperflevel high || true
    '';
  };

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  services.hardware.bolt.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3efe8a3c-3220-4a66-bec0-5c606af6e7bb";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/286E-87AC";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/scratch" = {
    device = "/dev/disk/by-uuid/cbbb4df8-e208-46ee-a6e4-4f9e631e4b3e";
    fsType = "btrfs";
  };

  systemd.settings.Manager = {
    RuntimeWatchdogSec = "30s";
    RebootWatchdogSec = "10min";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
