{
  config,
  lib,
  inputs,
  ...
}:
{
  imports = [ inputs.agenix.nixosModules.default ];

  # Host key works on every machine (generated by sshd at first boot);
  # user keys add convenient identities for personal secrets on owner devices.
  age.identityPaths = [
    "/etc/ssh/ssh_host_ed25519_key"
  ]
  ++ lib.optional config.systemOptions.owner.e.enable "/home/e-work/.ssh/id_ed25519"
  ++ lib.optionals config.systemOptions.owner.v.enable [
    "/home/v-work/.ssh/id_ed25519"
    "/home/v-play/.ssh/id_ed25519"
  ];

  age.secrets = lib.mkMerge [
    (lib.mkIf config.systemOptions.owner.e.enable {
      onyx-ssh-config = {
        file = ../../secrets/onyx-ssh-config.age;
        owner = "e-work";
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.dyndns.enable {
      namecheap-ddns = {
        file = ../../secrets/namecheap-ddns.age;
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.bastion.enable {
      # owner=mu because the wake-and-relay script runs as user `mu` (invoked
      # via ssh ProxyCommand by clients), so it needs read access to these.
      e-desktop-luks-passphrase = {
        file = ../../secrets/e-desktop-luks-passphrase.age;
        owner = "mu";
        mode = "0400";
      };
      bastion-initrd-unlock-key = {
        file = ../../secrets/bastion-initrd-unlock-key.age;
        owner = "mu";
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.nextcloud.enable {
      nextcloud-admin-password = {
        file = ../../secrets/nextcloud-admin-password.age;
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.grafana.enable {
      # Read at startup by the grafana service (runs as the grafana user).
      grafana-admin-password = {
        file = ../../secrets/grafana-admin-password.age;
        owner = "grafana";
        mode = "0400";
      };
      grafana-secret-key = {
        file = ../../secrets/grafana-secret-key.age;
        owner = "grafana";
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.searxng.enable {
      # Read by the searx service (runs as user `searx`) as an EnvironmentFile;
      # provides $SEARX_SECRET_KEY referenced from settings.server.secret_key.
      searxng-secret-key = {
        file = ../../secrets/searxng-secret-key.age;
        owner = "searx";
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.signal-cli.enable {
      # signal-cli reads SIGNAL_PHONE (the bot's number) from this file.
      # Runs as user `signal-cli`.
      signal-cli-env = {
        file = ../../secrets/signal-cli-env.age;
        owner = "signal-cli";
        group = "signal-cli";
        mode = "0440";
      };
    })
    # LiteLLM master key (file content: LITELLM_MASTER_KEY=sk-...).
    (lib.mkIf config.systemOptions.services.litellmProxy.enable {
      # Read by the litellm container (bind-mounted as root) and by the
      # open-webui service (its wrapper exports OPENAI_API_KEYS from it).
      litellm-master-key = {
        file = ../../secrets/litellm-master-key.age;
        group = "open-webui";
        mode = "0440";
      };
      # DeepSeek API key for the hosted models (file content: DEEPSEEK_API_KEY=sk-...).
      litellm-deepseek-key = {
        file = ../../secrets/litellm-deepseek-key.age;
        mode = "0400";
      };
    })
    # Son of Anton gateway secrets (content: SIGNAL_ACCOUNT=..., plus
    # optional DISCORD_BOT_TOKEN / SLACK_BOT_TOKEN / SLACK_APP_TOKEN).
    #
    # One file, read by every instance: they share a Signal account, so they
    # need the same SIGNAL_ACCOUNT. Group-readable rather than owned by one
    # account — the instances run as separate users (e-work, e-play,
    # soa-house) and `son-of-anton` is now only the group that grants this
    # read. 0440, never 0444: the group is the boundary.
    (lib.mkIf config.systemOptions.services.son-of-anton.enable {
      son-of-anton-env = {
        file = ../../secrets/son-of-anton-env.age;
        group = "son-of-anton";
        mode = "0440";
      };

      # Per-instance routing. Every service sees every Signal event (signal-cli
      # broadcasts over SSE) and keeps only its own group, so
      # SIGNAL_GROUP_ALLOWED_USERS is what makes one of them answer and the
      # others stay silent. Encrypted rather than written in Nix because this
      # repo is public and a group id names a real chat.
      #
      # Appended AFTER son-of-anton-env, so a re-declared key here wins.
      son-of-anton-work-env = {
        file = ../../secrets/son-of-anton-work-env.age;
        group = "son-of-anton";
        mode = "0440";
      };
      son-of-anton-play-env = {
        file = ../../secrets/son-of-anton-play-env.age;
        group = "son-of-anton";
        mode = "0440";
      };
      # Also re-declares SIGNAL_ALLOWED_USERS with the household members. The
      # shared secret keeps the single-owner allowlist, so widening it here
      # cannot widen work or play.
      son-of-anton-house-env = {
        file = ../../secrets/son-of-anton-house-env.age;
        group = "son-of-anton";
        mode = "0440";
      };
    })
    (lib.mkIf config.systemOptions.owner.e.enable {
      # Read by the opencode wrapper script (runs as e-work / e-play),
      # which sources this file to provide $LITELLM_MASTER_KEY.
      litellm-master-key = {
        file = ../../secrets/litellm-master-key.age;
        group = "users";
        mode = "0440";
      };
    })
    (lib.mkIf config.systemOptions.owner.v.enable {
      # Same as the e-device block, for v-work / v-play.
      litellm-master-key = {
        file = ../../secrets/litellm-master-key.age;
        group = "users";
        mode = "0440";
      };
    })
    (lib.mkIf config.services.protonmail-bridge.enable {
      # Proton Bridge IMAP/SMTP credentials for the proton-mcp opencode server.
      # Read at runtime by the proton-mcp wrapper (opencode runs as e-play),
      # which sources this file for PROTON_BRIDGE_* env vars.
      proton-mail-bridge = {
        file = ../../secrets/proton-mail-bridge.age;
        owner = "e-play";
        mode = "0400";
      };
    })
  ];
}
