{
  config,
  lib,
  inputs,
  ...
}:
{
  imports = [ inputs.agenix.nixosModules.default ];

  # Host key works on every machine (generated by sshd at first boot);
  # user key adds a convenient identity on e-devices for personal secrets.
  age.identityPaths = [
    "/etc/ssh/ssh_host_ed25519_key"
  ]
  ++ lib.optional config.systemOptions.owner.e.enable "/home/e-work/.ssh/id_ed25519";

  age.secrets = lib.mkMerge [
    (lib.mkIf config.systemOptions.owner.e.enable {
      onyx-ssh-config = {
        file = ../../secrets/onyx-ssh-config.age;
        owner = "e-work";
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.dyndns.enable {
      namecheap-ddns = {
        file = ../../secrets/namecheap-ddns.age;
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.bastion.enable {
      # owner=mu because the wake-and-relay script runs as user `mu` (invoked
      # via ssh ProxyCommand by clients), so it needs read access to these.
      e-desktop-luks-passphrase = {
        file = ../../secrets/e-desktop-luks-passphrase.age;
        owner = "mu";
        mode = "0400";
      };
      bastion-initrd-unlock-key = {
        file = ../../secrets/bastion-initrd-unlock-key.age;
        owner = "mu";
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.nextcloud.enable {
      nextcloud-admin-password = {
        file = ../../secrets/nextcloud-admin-password.age;
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.security.harden.enable {
      # Read by the cve-scan service (runs as root) to publish reports to ntfy.
      ntfy-publish-token = {
        file = ../../secrets/ntfy-publish-token.age;
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.grafana.enable {
      # Read at startup by the grafana service (runs as the grafana user).
      grafana-admin-password = {
        file = ../../secrets/grafana-admin-password.age;
        owner = "grafana";
        mode = "0400";
      };
      grafana-secret-key = {
        file = ../../secrets/grafana-secret-key.age;
        owner = "grafana";
        mode = "0400";
      };
    })
    # LiteLLM master key (file content: LITELLM_MASTER_KEY=sk-...).
    (lib.mkIf config.systemOptions.services.litellmProxy.enable {
      # son-of-anton: read by the proxy as a systemd EnvironmentFile (as root,
      # then bind-mounted into the litellm container). Root-only.
      litellm-master-key = {
        file = ../../secrets/litellm-master-key.age;
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.services.searxng.enable {
      # Read by the searx service (runs as user `searx`) as an EnvironmentFile;
      # provides $SEARX_SECRET_KEY referenced from settings.server.secret_key.
      searxng-secret-key = {
        file = ../../secrets/searxng-secret-key.age;
        owner = "searx";
        mode = "0400";
      };
    })
    (lib.mkIf config.systemOptions.owner.e.enable {
      litellm-master-key = {
        file = ../../secrets/litellm-master-key.age;
        owner = "e-work";
        group = "users";
        mode = "0440";
      };
    })
  ];
}
